from app.services.llms.base import BaseLLMClient


class MockLLMClient(BaseLLMClient):
    def generate(self, prompt: str) -> str:
        return (
            "This is a mock RAG answer generated based on the retrieved context. "
            "In the production version, this response will be generated by a real LLM."
        )